.PHONY: all clean

OUTDIR := summary

all: $(OUTDIR)/summary.pdf

DATA := $(wildcard out/*.pgf out/*.tex)

export TEXINPUTS := $(TEXINPUTS):out:

$(OUTDIR)/summary.pdf: summary.tex $(DATA)
	latexrun -O $(OUTDIR) $< -o $ $@

clean:
	rm -rf $(OUTDIR)
